# Generated by Django 5.0 on 2024-03-09 11:59

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 9, 14, 59, 19, 991695), null=True, verbose_name='Дата отправки')),
                ('message_id', models.CharField(blank=True, default='', max_length=100, verbose_name='id сообщения')),
                ('status', models.BooleanField(default=True, verbose_name='Статус отправки')),
            ],
            options={
                'verbose_name': 'Сообщение в telegram',
                'verbose_name_plural': 'Сообщения в telegram',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(default='example', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('phone', models.CharField(blank=True, default='', max_length=12)),
                ('email', models.EmailField(blank=True, default='example@mail.com', max_length=254, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Users', verbose_name='Фото')),
                ('is_telegram_use', models.BooleanField(blank=True, default=False, verbose_name='Telegram привязан')),
                ('telegram_id', models.CharField(blank=True, default='', max_length=12, verbose_name='Telegram id')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение в чате',
                'verbose_name_plural': 'Сообщения в чате',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи чата')),
                ('messages', models.ManyToManyField(blank=True, to='users.chatmessage', verbose_name='сообщения')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
    ]
