# Generated by Django 5.0 on 2024-03-09 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 9, 14, 59, 54, 839322), null=True, verbose_name='Дата отправки'),
        ),
    ]
